<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Sum" Id="{267ee07b-df51-4d9e-9956-8cf1d2e5412a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Sum : LREAL
VAR_INPUT
    var1 : LREAL;
    var2 : LREAL;
END_VAR
VAR
    total : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Body]]></ST>
    </Implementation>
    <LineIds Name="Sum">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>