<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_Simple" Id="{7b81e162-46f6-4a08-85f1-6c0ae9b32d13}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Simple
VAR
	boolean : BOOL := TRUE;
END_VAR    
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// No code here]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>