<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Sum" Id="{492f8b92-2688-4908-bea0-340aa3fead5f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Sum : LREAL
VAR_INPUT
    var1 : LREAL;
    var2 : LREAL;
END_VAR
VAR
    total : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Body]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>