<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_Base" Id="{a64c0680-a1e5-408a-bb5b-a6bff69faebe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Base
VAR_INPUT
    Variable1 : INT;
    Variable2   : DINT;
    Variable3   :REAL;
    Sentence : T_MaxString;
    Conditions : ARRAY[1..6] OF BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>