on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
      - run: |
          dotnet tool install --global csharpier
          dotnet tool install --global fantomas
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.0
        if: always()
